# Generated by Django 4.2 on 2023-04-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customuser_commande_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customuser'),
        ),
    ]
