# Generated by Django 4.2 on 2023-05-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
