# Generated by Django 4.2 on 2023-05-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_customuser_email'),
    ]

    operations = [
    ]
