# Generated by Django 4.2 on 2023-05-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20230505_2156'),
    ]

    operations = [
    ]
